export const post = [
  {
    points: 88,
    author: "tutu",
    id: 1,
    title:
      "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    date: "2020-08-01T10:51:36.790Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "quia et suscipit\nsuscipit recusandae consequuntur eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volueveniexpedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
  },
  {
    points: 111,
    id: 2,
    author: "hạ anh",
    title: "qui est esse",
    date: "2020-07-28T23:36:17.929Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "est rerum tempore vitae\nsequi sint nihil eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volueveni reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
  },
  {
    points: 221,
    id: 3,
    author: "anthony",
    title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    date: "2020-07-26T17:01:17.194Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "et iusto sed quo iure\nvoluptatem occaecati eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volueveni omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
  },
  {
    points: 899,
    id: 4,
    author: "anh tú",
    title: "eum et est occaecati",
    date: "2020-05-08T14:11:59.604Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
  },
  {
    points: 90,
    id: 5,
    author: "anh tú",
    title: "nesciunt quas odio",
    date: "2019-04-01T10:17:24.185Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
  },
  {
    points: 22,
    id: 6,
    author: "anh tú",
    title: "dolorem eum magni eos aperiam quia",
    date: "2020-01-28T09:15:04.904Z",
    comments: [],
    content:
      "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
  },
  {
    points: 33,
    id: 7,
    author: "anh tú",
    title: "magnam facilis autem",
    date: "2019-12-23T07:42:02.383Z",
    comments: [],
    content:
      "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
  },
  {
    points: 77,
    id: 8,
    author: "anh tú",
    title: "dolorem dolore est ipsam",
    date: "2019-11-18T21:31:17.178Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },

      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "dignissimos aperiam dolorem qeveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volueveniui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
  },
  {
    points: 111,
    id: 9,
    author: "anh tú",
    title: "nesciunt iure omnis dolorem tempora et accusantium",
    date: "2019-11-18T21:31:17.178Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
  },
  {
    points: 231,
    id: 10,
    author: "anh tú",
    title: "optio molestias id quia eum",
    date: "2019-11-18T21:31:17.178Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
  },
  {
    points: 232,
    id: 11,
    author: "anh tú",
    title: "et ea vero quia laudantium autem",
    date: "2019-11-18T21:31:17.178Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi",
  },
  {
    points: 412,
    id: 12,
    author: "anh tú",
    title: "in quibusdam tempore odit est dolorem",
    date: "2019-11-01T13:15:33.035Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio",
  },
  {
    points: 312,
    id: 13,
    author: "anh tú",
    title: "dolorum ut in voluptas mollitia et saepe quo animi",
    date: "2019-11-30T09:48:16.867Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam",
  },
  {
    points: 123,
    id: 14,
    author: "anh tú",
    title: "voluptatem eligendi optio",
    date: "2019-11-30T09:48:16.867Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum",
  },
  {
    points: 867,
    id: 15,
    author: "anh tú",
    title: "eveniet quod temporibus",
    date: "2020-01-25T14:18:46.235Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae",
  },
  {
    points: 221,
    id: 16,
    author: "anh tú",
    title: "sint suscipit perspiciatis velit dolorum ",
    date: "2020-01-25T14:18:46.235Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta",
  },
  {
    points: 664,
    id: 17,
    author: "anh tú",
    title: "fugit voluptas sed molestias voluptatem provident",
    date: "2020-01-25T14:18:46.235Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo",
  },
  {
    points: 538,
    id: 18,
    author: "anh tú",
    title: "voluptate et itaque vero tempora molestiae",
    date: "2019-06-25T18:49:59.371Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volueveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voleveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volptatem vel debitis et magnam",
  },
  {
    points: 187,
    id: 19,
    author: "anh tú",
    title: "adipisci placeat illum aut reiciendis qui",
    date: "2020-04-10T14:43:26.374Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "illum quis cupiditate provident sit magnam\nea sed aut omnis\nvenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluevenieveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest volueveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas",
  },
  {
    points: 218,
    id: 20,
    author: "anh tú",
    title: "doloribus ad provident suscipit at",
    date: "2019-03-10T14:43:26.374Z",
    comments: [
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/matt.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/joe.jpg",
        name: "Elliot Fu",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
      {
        content: "aut facere repellat provident occaecati",
        avt: "https://react.semantic-ui.com/images/avatar/small/jenny.jpg",
        name: "Matt",
        time: "2020-08-01T10:51:36.790Z",
      },
    ],
    content:
      "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo",
  },
];
